### ISSUE TITLE
Add detection if IP interfaces and print acces ednpoint during start

### ISSUE THREAD

**Issue by bakibakis** [netioproducts/netio-data-collector#1]
Detect system IP address and print address of ednpoint wchich should be filled in netio devices.

Print:
e.g.: Set Netio push API destination address to: "http://192.168.1.222:9000/push/json"

Windows and Linux support

**Comment by AdamVerner** [comment]
While F-strings are really great feature, they are only supported only from
3.6+ which discredits some older distributions (e.g.: default ubuntu 16.04)

Personal opinion:
Calling functions from strings is really obscure.

As for the `get_ip()` function it could collide with argument `--host`
which is used to specify outgoing interface

Also you should not be printing localhost for users to copy-paste into
their devices.

**Comment by jsperlnetio** [comment]
@AdamVerner 
As for the f-string, it's a habit from C#, using functions from f-strings seems handy to me when the value you need is only going to be printed and never needs to be stored in memory.
I also thought the repo targets python 3.6+ as you have previously written in the "Requirements" portion of readme.md, but if we want to support older python I'll be happy to remake it.

As for the IP, the function is called `get_local_ip()` and it gets ip that is bound to the default route. Could you please provide steps to reproduce it returning `localhost`. Because in my testing it returns the correct IP on all of my devices on Linux, Windows and Android.
e.g.:
![image](https://user-images.githubusercontent.com/54618784/64323141-2dc5fb00-cfc4-11e9-8888-1071aedc2a6e.png)

**Comment by AdamVerner** [comment]
Collision with `--host` example

i have three network interfaces (lan, wifi, vpn)
```
$ ./main.py --host 127.0.0.1
Sat Sep  7 11:37:00 2019 Server Starts - 127.0.0.1:9000
Device - Target host HTTP server: 172.18.17.4:9000/push/json
^CSat Sep  7 11:37:02 2019 Server Stops - 127.0.0.1:9000
```
or 
```
$  ./main.py --host 192.168.20.51
Sat Sep  7 11:43:35 2019 Server Starts - 192.168.20.51:9000
Device - Target host HTTP server: 172.18.17.4:9000/push/json
^CSat Sep  7 11:43:39 2019 Server Stops - 192.168.20.51:9000
```

as for the localhost if I do not have any interface configured it prints localhost

```
$ ./main.py
Sat Sep  7 11:45:12 2019 Server Starts - 0.0.0.0:9000
Device - Target host HTTP server: 127.0.0.1:9000/push/json
^CSat Sep  7 11:45:14 2019 Server Stops - 0.0.0.0:9000
```

**Comment by AdamVerner** [comment]
also if you want to use f-string, be consistent and change all other string formating in the whole repo

**Comment by jsperlnetio** [comment]
I'll change it back, it was just a force of habit, I don't need f-strings.


As for the IP portion, I'm not really well versed in netcode, so this is the best solution on my part, if you have an idea how to implement it so it satisfies your needs please give it a shot.
